version: "3.9"
services:
  spring-app:
    container_name: spring-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql-db:5432/bloomberg
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
    networks:
      - bloomberg
    depends_on:
      - psql-db
  psql-db:
    container_name: psql-db
    image: "postgres:15"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "bloomberg"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - bloomberg

#  sonarqube:
#    image: sonarqube:lts
#    ports:
#      - "9000:9000"
#    networks:
#      - youquiz
#    environment:
#      - SONAR_FORCEAUTHENTICATION=false
#  prometheus:
#    image: prom/prometheus:v2.44.0
#    container_name: prometheus
#    networks:
#      - bloomberg
#    ports:
#      - "9090:9090"
#    volumes:
#      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
#  grafana:
#    image: grafana/grafana:9.5.2
#    container_name: grafana
#    networks:
#      - bloomberg
#    ports:
#      - "3000:3000"
#    restart: unless-stopped
#    volumes:
#      - ./monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources

networks:
  bloomberg:
    driver: bridge

volumes:
  postgres-db:
    driver: local